# For info about .codeclimate.yml structure see:
# https://docs.codeclimate.com/docs/advanced-configuration

version: "2"         # required to adjust maintainability checks

# See: https://docs.codeclimate.com/docs/maintainability#section-checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

# See: https://docs.codeclimate.com/docs/advanced-configuration#section-plugins
# and https://docs.codeclimate.com/docs/list-of-engines
plugins:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
    config:
      config: templates/linters/.eslintrc.json
      extensions:
      - .es6
      - .js
      - .jsx
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  rubocop:
    enabled: true
    config:
      file: templates/linters/.rubocop.yml
  reek:
    enabled: true
    config:
      config: templates/linters/config.reek
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
