# https://rubocop.readthedocs.io/
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - config.ru
  Exclude:
    - db/schema.rb

# Longer line length
Metrics/LineLength:
  Max: 140

# Methods can be 20 lines long
Metrics/MethodLength:
  Max: 10

# Prefer raise over fail
Style/SignalException:
  EnforcedStyle: only_raise

# Make literal hashes act like arrays
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Disable the documentation requirement
Style/Documentation:
  Enabled: false

# Allow the usage of begin blocks
Style/BeginBlock:
  Enabled: false

# Force Ruby 1.9 syntax and do not mix key types
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Array indentation has to be consistent, but it is more flexible
Layout/IndentArray:
  EnforcedStyle: consistent

# Hash indentation has to be consistent, but it is more flexible
Layout/IndentHash:
  EnforcedStyle: consistent

# Use rails indentation
Layout/IndentationConsistency:
  EnforcedStyle: normal

# Do not trail do end blocks with extra function calls
Style/MethodCalledOnDoEndBlock:
  Enabled: true

# Do not enforce the use of `next if <condition>` instead of `unless <condition> ... end`
Style/Next:
  Enabled: false

# Complex inline ifs need ()
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/StringLiterals:
  # Enforcing double quotes reduces the times where you need to change them
  EnforcedStyle: double_quotes
  # Use consistent quotes when multi-lining strings
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: false

# Allow usage :"symbol"
Style/SymbolLiteral:
  Enabled: false

# We usally only flatten only level so we can enable this feature
Performance/FlatMap:
  EnabledForFlattenWithoutParams: true

# Force strict date getting to it handles better with activerecord dates
Rails/Date:
  EnforcedStyle: strict

# Rails 5 cop
Rails/HttpPositionalArguments:
  Enabled: false

# No need to sort gems in the bundle file
Bundler/OrderedGems:
  Enabled: false

# Don't check on block length in spec files.
# `describe` and `context` blocks can be large.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

# Do not suggest to rename `has_x?` to `x?`
Naming/PredicateName:
  Enabled: false
