sudo: required
services:
  - docker
matrix:
  include:
    - language: ruby
      before_install:
        - gem install bundler
      rvm:
        - 2.5.1@launch-base --create
      install:
        - bin/setup
      script:
        - bin/ci
      addons:
        chrome: stable
    - language: node_js
      node_js:
        - "8"
      script:
        -  npm run test-eslint
