sudo: required
matrix:
  include:
    - language: ruby
      install:
        - bin/setup
      script:
        - bundle exec rubocop -c templates/linters/.rubocop.yml test/linters/ruby.rb
        - bundle exec reek -c templates/linters/config.reek test/linters/ruby.rb
        - bundle exec rake test
    - language: node_js
      node_js:
        - "8"
      script:
        -  npm run test-eslint
