sudo: required
matrix:
  include:
    - language: ruby
      rvm:
        - 2.5.1@launch-base
      before_install:
        - gem install bundler
      install:
        - bin/setup
      script:
        - bin/ci
    - language: node_js
      node_js:
        - "8"
      script:
        -  npm run test-eslint
